version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=obj_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
